version: '2.1'

services:
  db:
    image: appropriate/nc
    command: /bin/sh -c 'echo server started && nc -lk 5432'
    ports:
      - "5432"

  db2:
    image: appropriate/nc
    command: /bin/sh -c 'echo server started && nc -lk 5432'
    ports:
      - "5432"

  db3:
    image: appropriate/nc
    command: /bin/sh -c 'echo server started && nc -lk 5432'
    ports:
      - "5432"

  db4:
    image: appropriate/nc
    command: /bin/sh -c 'echo server started && nc -lk 5432'
    ports:
      - "5432"
